### ISSUE TITLE
how to delete a unused tag

### ISSUE THREAD

**Issue by wqingzex** [gabrielgodoy-zz/github-stars-manager#4]

**Comment by gabrielgodoy-zz** [comment]
@qingzew , If a tag is unused it is supposed to be automatically deleted

**Comment by wqingzex** [comment]
there is no anything under the tag, but it's there

**Comment by gabrielgodoy-zz** [comment]
Hi @qingzew 

Now on version 1.3 you can delete tags directly

![image](https://user-images.githubusercontent.com/2944970/26995237-e05d2bce-4d41-11e7-8773-b2b63b21eef0.png)

To update the extension to 1.3, maybe you have to go to  **chrome://extensions/** and click on the button "Update extensions now"

Hope this helps!

[]'s

**Comment by wqingzex** [comment]
@gabrielgodoy thanks
